module PcfgTransforms.Title exposing (title)

import Pcfg exposing (Transform, literalForm, concatForms, pickWeightedForm)


title : Transform
title =
  { name = "Title"
  , description = "Heroic titles"
  , priority = 1
  , transform = transformName
  }


transformName name =
  let titled_name _ = pickWeightedForm
        [ (10.0, concatForms [name, the, description])
        , (5.0, concatForms [name, of_the, sigil_phrase])
        , (1.0, concatForms [adjective, sp, name])
        ]

      the = literalForm " the "

      of_the = literalForm " of the "

      sp = literalForm " "

      color _ = pickWeightedForm
        [ (1.0, literalForm "Golden")
        , (1.0, literalForm "Silver")
        , (1.0, literalForm "Argent")
        , (1.0, literalForm "Sable")
        , (1.0, literalForm "Red")
        , (1.0, literalForm "Blue")
        , (1.0, literalForm "Green")
        , (1.0, literalForm "White")
        , (1.0, literalForm "Orange")
        , (1.0, literalForm "Black")
        , (1.0, literalForm "Grey")
        , (1.0, literalForm "Yellow")
        , (1.0, literalForm "Purple")
        , (1.0, literalForm "Chartreuse")
        , (1.0, literalForm "Crimson")
        , (1.0, literalForm "Azure")
        , (1.0, literalForm "Violet")
        , (1.0, literalForm "Magenta")
        , (1.0, literalForm "Brown")
        , (1.0, literalForm "Beige")
        , (1.0, literalForm "Indigo")
        , (1.0, literalForm "Cyan")
        ]

      material _ = pickWeightedForm
        [ (1.0, literalForm "Stone")
        , (1.0, literalForm "Golden")
        , (1.0, literalForm "Iron")
        , (1.0, literalForm "Clay")
        , (1.0, literalForm "Crystalline")
        , (1.0, literalForm "Jade")
        , (1.0, literalForm "Amber")
        , (1.0, literalForm "Glass")
        ]

      sigil_phrase _ = pickWeightedForm
        [ (2.0, concatForms [sigil_mod_s, sp, sigil])
        , (2.0, concatForms [sigil_mod_pl, sp, sigil, literalForm "s"])
        , (1.0, sigil)
        , (1.0, concatForms [sigil, literalForm "s"])
        ]

      sigil_mod_s _ = pickWeightedForm
        [ (4.0, color)
        , (4.0, material)
        , (1.0, literalForm "Majestic")
        , (1.0, literalForm "Great")
        , (1.0, literalForm "Noble")
        , (1.0, literalForm "Fallen")
        , (1.0, literalForm "Broken")
        , (1.0, literalForm "Cloven")
        , (1.0, literalForm "Lost")
        , (1.0, literalForm "Cursed")
        , (1.0, literalForm "Blessed")
        , (1.0, literalForm "Ancient")
        ]

      sigil_mod_pl _ = pickWeightedForm
        [ (3.0, sigil_mod_s)
        , (3.0, color)
        , (1.0, literalForm "Two")
        , (1.0, literalForm "Twin")
        , (1.0, literalForm "Three")
        , (1.0, literalForm "Four")
        , (1.0, literalForm "Five")
        , (1.0, literalForm "Six")
        , (1.0, literalForm "Seven")
        , (1.0, literalForm "Nine")
        , (1.0, literalForm "Dozen")
        , (1.0, literalForm "Multitudinous")
        ]

      sigil _ = pickWeightedForm
        [ (1.0, literalForm "Bear")
        , (1.0, literalForm "Lion")
        , (1.0, literalForm "Boar")
        , (1.0, literalForm "Cat")
        , (1.0, literalForm "Toad")
        , (1.0, literalForm "Owl")
        , (1.0, literalForm "Bat")
        , (1.0, literalForm "Rat")
        , (1.0, literalForm "Raven")
        , (1.0, literalForm "Dove")
        , (1.0, literalForm "Scorpion")
        , (1.0, literalForm "Snake")
        , (1.0, literalForm "Swan")
        , (1.0, literalForm "Dragon")
        , (1.0, literalForm "Diamond")
        , (1.0, literalForm "Crystal")
        , (1.0, literalForm "Stone")
        , (1.0, literalForm "Spear")
        , (1.0, literalForm "Blade")
        , (1.0, literalForm "Sword")
        , (1.0, literalForm "Bow")
        , (1.0, literalForm "Arrow")
        , (1.0, literalForm "Dagger")
        , (1.0, literalForm "Club")
        , (1.0, literalForm "Lance")
        , (1.0, literalForm "Hammer")
        , (1.0, literalForm "Axe")
        , (1.0, literalForm "Shield")
        , (1.0, literalForm "Mantle")
        , (1.0, literalForm "Gauntlet")
        , (1.0, literalForm "Helm")
        , (1.0, literalForm "Crown")
        , (1.0, literalForm "Mask")
        , (1.0, literalForm "Wand")
        , (1.0, literalForm "Orb")
        , (1.0, literalForm "Scroll")
        , (1.0, literalForm "Tome")
        , (1.0, literalForm "Gate")
        , (1.0, literalForm "Tower")
        , (1.0, literalForm "Door")
        , (1.0, literalForm "Pyramid")
        , (1.0, literalForm "Manse")
        , (1.0, literalForm "Tomb")
        , (1.0, literalForm "Spire")
        , (1.0, literalForm "River")
        , (1.0, literalForm "Grove")
        , (1.0, literalForm "Mountain")
        , (1.0, literalForm "Shore")
        , (1.0, literalForm "Tarn")
        , (1.0, literalForm "Desert")
        , (1.0, literalForm "Glen")
        , (1.0, literalForm "Moon")
        , (1.0, literalForm "Sun")
        , (1.0, literalForm "Star")
        , (1.0, literalForm "Clover")
        , (1.0, literalForm "Rose")
        , (1.0, literalForm "Oak")
        , (1.0, literalForm "Elm")
        , (1.0, literalForm "Bean")
        , (1.0, literalForm "Fist")
        , (1.0, literalForm "Heart")
        , (1.0, literalForm "Skull")
        , (1.0, literalForm "Bone")
        , (1.0, literalForm "Claw")
        , (1.0, literalForm "Talon")
        , (1.0, literalForm "Hand")
        , (1.0, literalForm "Eye")
        , (1.0, literalForm "Horn")
        , (1.0, literalForm "Flame")
        , (1.0, literalForm "Wave")
        , (1.0, literalForm "Cloud")
        , (1.0, literalForm "Snowflake")
        , (1.0, literalForm "Candle")
        , (1.0, literalForm "Chain")
        , (1.0, literalForm "Coin")
        , (1.0, literalForm "Lantern")
        ]

      adjective _ = pickWeightedForm
        [ (5.0, color)
        , (5.0, digit_adj)
        , (1.0, literalForm "Shark-toothed")
        , (1.0, literalForm "Half-dead")
        , (1.0, literalForm "One-eyed")
        , (1.0, literalForm "One-eared")
        , (1.0, literalForm "Fingerless")
        , (1.0, literalForm "Crooked")
        ]

      digit_adj _ = pickWeightedForm
        [ (3.0, concatForms [digit_count, literalForm "-fingered"])
        , (1.0, concatForms [digit_count, literalForm "-toed"])
        ]

      digit_count _ = pickWeightedForm
        [ (1.0, literalForm "Four")
        , (2.0, literalForm "Six")
        , (2.0, literalForm "Seven")
        , (1.0, literalForm "Eight")
        , (2.0, literalForm "Nine")
        , (1.0, literalForm "Eleven")
        ]

      description _ = pickWeightedForm
        [ (12.0, color)
        , (1.0, literalForm "Quick")
        , (1.0, literalForm "Nimble")
        , (1.0, literalForm "Feeble")
        , (1.0, literalForm "Strong")
        , (1.0, literalForm "Enduring")
        , (1.0, literalForm "Lean")
        , (1.0, literalForm "Stout")
        , (1.0, literalForm "Tall")
        , (1.0, literalForm "Fat")
        , (1.0, literalForm "Giant")
        , (1.0, literalForm "Incompetent")
        , (1.0, literalForm "Daft")
        , (1.0, literalForm "Half-Wit")
        , (1.0, literalForm "Silver-Tongued")
        , (1.0, literalForm "Clever")
        , (1.0, literalForm "Mad")
        , (1.0, literalForm "Great")
        , (1.0, literalForm "Wise")
        , (1.0, literalForm "Brave")
        , (1.0, literalForm "Honest")
        , (1.0, literalForm "Mighty")
        , (1.0, literalForm "Pious")
        , (1.0, literalForm "Noble")
        , (1.0, literalForm "Spineless")
        , (1.0, literalForm "Craven")
        , (1.0, literalForm "Fool")
        , (1.0, literalForm "Liar")
        , (1.0, literalForm "Vague")
        , (1.0, literalForm "Cordial")
        , (1.0, literalForm "Crabby")
        , (1.0, literalForm "Incongruously Cheerful")
        , (1.0, literalForm "Reckless")
        , (1.0, literalForm "Unladylike")
        , (1.0, literalForm "Truculent")
        , (1.0, literalForm "Flirtatious")
        , (1.0, literalForm "Boorish")
        , (1.0, literalForm "Forthright")
        , (1.0, literalForm "Swanky")
        , (1.0, literalForm "Inconsistent")
        , (1.0, literalForm "Lunatic")
        , (1.0, literalForm "Quiet")
        , (1.0, literalForm "Merciful")
        , (1.0, literalForm "Maniac")
        , (1.0, literalForm "Deathless")
        , (1.0, literalForm "Dragonslayer")
        , (1.0, literalForm "Titan-killer")
        , (1.0, literalForm "Magnificent")
        , (1.0, literalForm "Revenant")
        , (1.0, literalForm "Invisible")
        , (1.0, literalForm "Blind")
        , (1.0, literalForm "Deaf")
        , (1.0, literalForm "Wrinkled")
        , (1.0, literalForm "Smelly")
        , (1.0, literalForm "Toothless")
        , (1.0, literalForm "Unblinking")
        , (1.0, literalForm "Beautiful")
        , (1.0, literalForm "Fair")
        , (1.0, literalForm "Plain")
        , (1.0, literalForm "Gassy")
        , (1.0, literalForm "Hirsute")
        , (1.0, literalForm "Bald")
        , (1.0, literalForm "Fearsome")
        , (1.0, literalForm "Slightly Off")
        , (1.0, literalForm "Bizarre")
        , (1.0, literalForm "Irksome")
        , (1.0, literalForm "Stand-up Guy")
        , (1.0, literalForm "Cruel")
        , (1.0, literalForm "Butcher")
        , (1.0, literalForm "Liar")
        , (1.0, literalForm "Freak")
        , (1.0, literalForm "Planetouched")
        , (1.0, literalForm "Fey")
        , (1.0, literalForm "Blessed")
        , (1.0, literalForm "Lucky")
        , (1.0, literalForm "Thrice-cursed")
        , (1.0, literalForm "Rich")
        , (1.0, literalForm "Poor")
        , (1.0, literalForm "Miserly")
        , (1.0, literalForm "Drunkard")
        , (1.0, literalForm "Sober")
        , (1.0, literalForm "Northron")
        , (1.0, literalForm "Southron")
        , (1.0, literalForm "Westron")
        , (1.0, literalForm "Eastron")
        , (1.0, literalForm "Beyonder")
        , (1.0, literalForm "Barbarian")
        , (1.0, literalForm "Poet")
        , (1.0, literalForm "Bard")
        , (1.0, literalForm "Singer")
        , (1.0, literalForm "Thief")
        , (1.0, literalForm "Warrior")
        , (1.0, literalForm "Archer")
        , (1.0, literalForm "Magician")
        , (1.0, literalForm "Witch")
        , (1.0, literalForm "Trapper")
        , (1.0, literalForm "Enchanter")
        , (1.0, literalForm "Artificer")
        , (1.0, literalForm "Sage")
        , (1.0, literalForm "Seer")
        , (1.0, literalForm "Pilgrim")
        , (1.0, literalForm "Wanderer")
        , (1.0, literalForm "Dragon")
        , (1.0, literalForm "Banshee")
        , (1.0, literalForm "Boar")
        , (1.0, literalForm "Leopard")
        , (1.0, literalForm "Eagle")
        , (1.0, literalForm "Cheetah")
        , (1.0, literalForm "Worm")
        , (1.0, literalForm "Toad")
        , (1.0, literalForm "Eel")
        , (1.0, literalForm "Rat")
        , (1.0, literalForm "Mouse")
        , (1.0, literalForm "Bear")
        , (1.0, literalForm "Snake")
        , (1.0, literalForm "Fox")
        , (1.0, literalForm "Cobra")
        , (1.0, literalForm "Flea")
        , (1.0, literalForm "Squid")
        , (1.0, literalForm "Spider")
        , (1.0, literalForm "Hawk")
        , (1.0, literalForm "Salamander")
        , (1.0, literalForm "Fish")
        , (1.0, literalForm "Weasel")
        , (1.0, literalForm "Tortoise")
        , (1.0, literalForm "Myrmidon")
        , (1.0, literalForm "Zephyr")
        ]
  in titled_name
